"vim-plug
call plug#begin()
	Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
	Plug 'mcchrish/nnn.vim'
	Plug 'sbdchd/neoformat'
	Plug 'ap/vim-css-color'
	Plug 'pangloss/vim-javascript'
	Plug 'neoclide/coc.nvim', {'branch': 'release'}
	Plug 'townk/vim-autoclose'
	Plug 'othree/html5.vim'
	Plug 'vimwiki/vimwiki'
call plug#end()

"vim-config
	set conceallevel=1
	set ic
	set nu rnu
	set wildmenu
	syntax on
	set tabstop=4
	set shiftwidth=4
	set noswapfile
	set hlsearch
	set incsearch
	set nocompatible
	set background=dark
	filetype plugin indent on
	set encoding=utf-8
	set splitbelow
	set splitright
	set clipboard=unnamed

"vim let
	let mapleader=","

"maps
	map <leader>. :FZF <CR>
	nnoremap <leader>n :NnnPicker %:p:h<CR>
	nnoremap <leader>f :CocCommand prettier.formatFile<cr>
	nnoremap <C-h> <C-w>h
	nnoremap <C-j> <C-w>j
	nnoremap <C-k> <C-w>k
	nnoremap <C-l> <C-w>l

let g:javascript_conceal_function             = "ƒ"
let g:javascript_conceal_null                 = "ø"
let g:javascript_conceal_this                 = "@"
let g:javascript_conceal_return               = "=>"
let g:javascript_conceal_undefined            = "¿"
let g:javascript_conceal_NaN                  = "ℕ"
let g:javascript_conceal_prototype            = "¶"
let g:javascript_conceal_static               = "•"
let g:javascript_conceal_super                = "Ω"

let g:nnn#layout = 'new'
let g:nnn#action = {
	      \ '<leader>t': 'tab split',
		  \ '<leader>s': 'split',
		  \ '<leader>v': 'vsplit' }

let g:neoformat_run_all_formatters = 1
let g:ale_completion_enabled = 1

